### ISSUE TITLE
non-working compose.yml

### ISSUE THREAD

**Issue by stefangweichinger** [bbtsoftware/docker-mssql-backup#12]
Your own example does not work.

The CRON_SCHEDULE leads to:

```
backup_1    | "/etc/cron.d/crontab.conf":0: bad minute
backup_1    | errors in crontab file, can't install.
```

In my opinion line 7 in your `docker-entrypoint.sh` does not handle the hyphens correctly.

**Comment by eoehen** [comment]
Thank you for your feedback. It's correct. There was a mistake in the the example. The value of CRON_SCHEDULE should not have quotes.

**Comment by stefangweichinger** [comment]
nice. I will test it by myself later this day.

**Comment by stefangweichinger** [comment]
I suggest fixing the Dockerfile as well.
But I think it won't work without the quotes. Will test.

**Comment by eoehen** [comment]
@stefangweichinger are you in a position to provide a pullrequest for supporting quotes?

**Comment by stefangweichinger** [comment]
Sure I can issue a PR. I also have ideas for adding a cleanup routine: delete backups older than X days .. etc
My local test seems to work with your commit, although to me the syntax seems a bit "flaky".
I'd like to generate the cronjob in a more robust way, but I have to think about it.

**Comment by eoehen** [comment]
@stefangweichinger many thanks for your constructive feedback. I have created three new issues from it.
- #14 
- #15 
- #16
