### ISSUE TITLE
Improve cronjob generation

### ISSUE THREAD

**Issue by eoehen** [bbtsoftware/docker-mssql-backup#15]
The generation of cronJobs should become more robust.

**Comment by stefangweichinger** [comment]
Maybe your syntax is ok ... as far as I google around ;-)
For example I find this: https://github.com/MorbZ/docker-cron
Quite the same approach.

**Comment by eoehen** [comment]
@stefangweichinger Do you agree if I close this issue?

**Comment by stefangweichinger** [comment]
ok with me, I just suggest. In my local fork I test things and might do it differently in the future.
