### ISSUE TITLE
Various feature requests

### ISSUE THREAD

**Issue by pfeigl** [bbtsoftware/docker-mssql-backup#20]
Hi - we found your wonderful docker image and would want some additions to it.

We could probably create a PR for most of it but before we go ahead and prepare everything, I wanted to check, what you guys think about the possible additions .

The additions we thought about:
* Allow reporting per e-mail (probably using MAILTO feature in crontab)
* Add option to tar.gz before writing to /backup
* Specifically with the gzip feature, we'd love to have an "intermediate" folder (i.e. /tmp) for creating the backups. Background is, that we actually mounted a remote-fs as /backup (sshfs or one could think of sftp or Amazon S3 or CIFS mounts). In those cases you would only want to write the packaged files there
* Add option to disable generation of transaction log backups

I'd map all those features to new ENV variables obviously, so that they are all optional and can be activated when needed.

**Comment by eoehen** [comment]
Thank you for your inspirations and the willingness to implement them yourself.
I will created new Issues for each new feature.

* [GH-21: Add option to disable generation of transaction log backups](https://github.com/bbtsoftware/docker-mssql-backup/issues/21)
* [GH-22: Add option to tar.gz](https://github.com/bbtsoftware/docker-mssql-backup/issues/22)
* [GH-23: Allow reporting per e-mail](https://github.com/bbtsoftware/docker-mssql-backup/issues/23)
* [GH-24: Add "intermediate" folder support](https://github.com/bbtsoftware/docker-mssql-backup/issues/24)

Thank you for your contribution.

**Comment by eoehen** [comment]
@pfeigl All Issues are created and linked. Let me know if it's okay when I close this one.

**Comment by pfeigl** [comment]
Cool, I'll probably have some time later this week to work on them. Guess you can close this ticket and I track progress on the new tickets.
