### ISSUE TITLE
Send log to stdout and stderr output streams only.

### ISSUE THREAD

**Issue by eoehen** [bbtsoftware/docker-mssql-backup#39]
If we add the parameter (-a) for append the logfile we have no control about the log file size.
We have to think how we can limite the log file size, before we activate this parameter.

- Remove support for write cron log file.
- Support to send log information to stdout and stderr output streams.

Feedback from @pfeigl in #37.

**Comment by pfeigl** [comment]
Coming from another direction: If the logfile is only created to be able to tail it and show all output in the docker logs, we could instead not create a log at all and write our output to `/proc/1/fd/1`, which is the stdout which docker connects to.

You can try it with `echo "hi" > /proc/1/fd/1` which will just show up in docker logs
